class Room {
  final String? id; // MongoDB _id
  final String name; // 'Board Room' | 'Conference Room'
  final int capacity;
  final List<String> equipment;
  final DateTime? createdAt; // auto-generated by backend
  final DateTime? updatedAt; // auto-generated by backend

  Room({
    this.id,
    required this.name,
    required this.capacity,
    required this.equipment,
    this.createdAt,
    this.updatedAt,
  });

  /// Create Room from backend JSON
  factory Room.fromJson(Map<String, dynamic> json) {
    return Room(
      id: json['_id'] ?? '',
      name: json['name'] ?? '',
      capacity: json['capacity'] ?? 0,
      equipment: List<String>.from(json['equipment'] ?? []),
      createdAt: json['createdAt'] != null ? DateTime.parse(json['createdAt']) : null,
      updatedAt: json['updatedAt'] != null ? DateTime.parse(json['updatedAt']) : null,
    );
  }

  /// Convert Room to JSON (for sending requests to backend)
  Map<String, dynamic> toJson() {
    return {
      '_id': id,
      'name': name,
      'capacity': capacity,
      'equipment': equipment,
      // createdAt & updatedAt are generated in backend, not required in requests
    };
  }
}
