import 'dart:convert';

class Attendee {
  final String name;
  final String email;

  Attendee({required this.name, required this.email});

  factory Attendee.fromJson(Map<String, dynamic> json) =>
      Attendee(name: json['name'], email: json['email']);

  Map<String, dynamic> toJson() => {'name': name, 'email': email};

    @override
  String toString() => 'Attendee(name: $name, email: $email)';

}

class Booking {
  final String? id;            // Auto-generated by backend
  final String roomId;         // Required
  final String? userId;        // From auth token
  final String? title;         // Optional
  final DateTime startTime;    // Required
  final DateTime endTime;      // Required
  final String? status;        // Optional, backend defaults to confirmed
  final List<Attendee>? attendees; // Optional
  final DateTime? createdAt;   // Auto-generated
  final DateTime? updatedAt;   // Auto-generated

  Booking({
    this.id,
    required this.roomId,
    this.userId,
    this.title,
    required this.startTime,
    required this.endTime,
    this.status,
    this.attendees,
    this.createdAt,
    this.updatedAt,
  });

  /// Factory for backend response
  factory Booking.fromJson(Map<String, dynamic> json) => Booking(
        id: json['_id'] as String?,
        roomId: json['roomId'] as String,
        userId: json['userId'] as String?,
        title: json['title'] as String?,
        startTime: DateTime.parse(json['startTime'] as String),
        endTime: DateTime.parse(json['endTime'] as String),
        status: json['status'] as String?,
        attendees: (json['attendees'] as List<dynamic>?)
            ?.map((a) => Attendee.fromJson(Map<String, dynamic>.from(a)))
            .toList(),
        createdAt: json['createdAt'] != null
            ? DateTime.parse(json['createdAt'] as String)
            : null,
        updatedAt: json['updatedAt'] != null
            ? DateTime.parse(json['updatedAt'] as String)
            : null,
      );

  /// To JSON for API request
  /// 
  Map<String, dynamic> toJson() => {
        'roomId': roomId,
        if (title != null) 'title': title,
        'startTime': startTime.toIso8601String(),
        'endTime': endTime.toIso8601String(),
        if (status != null) 'status': status,
        if (attendees != null)
          'attendees': attendees!.map((a) => a.toJson()).toList(),
      };

  /// copyWith creates a new object for frontend, doesn't affect backend
  Booking copyWith({
    String? id,
    String? roomId,
    String? userId,
    String? title,
    DateTime? startTime,
    DateTime? endTime,
    String? status,
    List<Attendee>? attendees,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return Booking(
      id: id ?? this.id,
      roomId: roomId ?? this.roomId,
      userId: userId ?? this.userId,
      title: title ?? this.title,
      startTime: startTime ?? this.startTime,
      endTime: endTime ?? this.endTime,
      status: status ?? this.status,
      attendees: attendees ?? this.attendees,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  /// Encode list of bookings
  static String encodeList(List<Booking> bookings) => json.encode(
        bookings.map((b) => b.toJson()).toList(),
      );

  /// Decode list of bookings
  static List<Booking> decodeList(String bookings) =>
      (json.decode(bookings) as List<dynamic>)
          .map((b) => Booking.fromJson(b))
          .toList();

    @override
      String toString() {
        return '''
    Booking(
      id: $id,
      roomId: $roomId,
      userId: $userId,
      title: $title,
      startTime: $startTime,
      endTime: $endTime,
      status: $status,
      attendees: $attendees,
      createdAt: $createdAt,
      updatedAt: $updatedAt
    )''';
    }

}
